package com.lecomapp.liquefied.core.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.colorResource
import com.lecomapp.liquefied.R

@Composable fun md_primary(): Color = colorResource(R.color.primary)
@Composable fun md_onPrimary(): Color = colorResource(R.color.on_primary)
@Composable fun md_primaryContainer(): Color = colorResource(R.color.primary_container)
@Composable fun md_onPrimaryContainer(): Color = colorResource(R.color.on_primary_container)
@Composable fun md_secondary(): Color = colorResource(R.color.secondary)
@Composable fun md_onSecondary(): Color = colorResource(R.color.on_secondary)
@Composable fun md_secondaryContainer(): Color = colorResource(R.color.secondary_container)
@Composable fun md_onSecondaryContainer(): Color = colorResource(R.color.on_secondary_container)
@Composable fun md_tertiary(): Color = colorResource(R.color.tertiary)
@Composable fun md_onTertiary(): Color = colorResource(R.color.on_tertiary)
@Composable fun md_tertiaryContainer(): Color = colorResource(R.color.tertiary_container)
@Composable fun md_onTertiaryContainer(): Color = colorResource(R.color.on_tertiary_container)
@Composable fun md_error(): Color = colorResource(R.color.error)
@Composable fun md_onError(): Color = colorResource(R.color.on_error)
@Composable fun md_errorContainer(): Color = colorResource(R.color.error_container)
@Composable fun md_onErrorContainer(): Color = colorResource(R.color.on_error_container)
@Composable fun md_background(): Color = colorResource(R.color.background)
@Composable fun md_onBackground(): Color = colorResource(R.color.on_background)
@Composable fun md_surface(): Color = colorResource(R.color.surface)
@Composable fun md_onSurface(): Color = colorResource(R.color.on_surface)
@Composable fun md_surfaceVariant(): Color = colorResource(R.color.surface_variant)
@Composable fun md_onSurfaceVariant(): Color = colorResource(R.color.on_surface_variant)
@Composable fun md_outline(): Color = colorResource(R.color.outline)
@Composable fun md_outlineVariant(): Color = colorResource(R.color.outline_variant)
@Composable fun md_inverseSurface(): Color = colorResource(R.color.inverse_surface)
@Composable fun md_inverseOnSurface(): Color = colorResource(R.color.inverse_on_surface)
@Composable fun md_inversePrimary(): Color = colorResource(R.color.inverse_primary)
@Composable fun md_surfaceTint(): Color = colorResource(R.color.surface_tint)
@Composable fun md_scrim(): Color = colorResource(R.color.scrim)

@Composable fun md_primaryDark(): Color = colorResource(R.color.primary_dark)
@Composable fun md_onPrimaryDark(): Color = colorResource(R.color.on_primary_dark)
@Composable fun md_primaryContainerDark(): Color = colorResource(R.color.primary_container_dark)
@Composable fun md_onPrimaryContainerDark(): Color = colorResource(R.color.on_primary_container_dark)
@Composable fun md_secondaryDark(): Color = colorResource(R.color.secondary_dark)
@Composable fun md_onSecondaryDark(): Color = colorResource(R.color.on_secondary_dark)
@Composable fun md_secondaryContainerDark(): Color = colorResource(R.color.secondary_container_dark)
@Composable fun md_onSecondaryContainerDark(): Color = colorResource(R.color.on_secondary_container_dark)
@Composable fun md_tertiaryDark(): Color = colorResource(R.color.tertiary_dark)
@Composable fun md_onTertiaryDark(): Color = colorResource(R.color.on_tertiary_dark)
@Composable fun md_tertiaryContainerDark(): Color = colorResource(R.color.tertiary_container_dark)
@Composable fun md_onTertiaryContainerDark(): Color = colorResource(R.color.on_tertiary_container_dark)
@Composable fun md_errorDark(): Color = colorResource(R.color.error_dark)
@Composable fun md_onErrorDark(): Color = colorResource(R.color.on_error_dark)
@Composable fun md_errorContainerDark(): Color = colorResource(R.color.error_container_dark)
@Composable fun md_onErrorContainerDark(): Color = colorResource(R.color.on_error_container_dark)
@Composable fun md_backgroundDark(): Color = colorResource(R.color.background_dark)
@Composable fun md_onBackgroundDark(): Color = colorResource(R.color.on_background_dark)
@Composable fun md_surfaceDark(): Color = colorResource(R.color.surface_dark)
@Composable fun md_onSurfaceDark(): Color = colorResource(R.color.on_surface_dark)
@Composable fun md_surfaceVariantDark(): Color = colorResource(R.color.surface_variant_dark)
@Composable fun md_onSurfaceVariantDark(): Color = colorResource(R.color.on_surface_variant_dark)
@Composable fun md_outlineDark(): Color = colorResource(R.color.outline_dark)
@Composable fun md_outlineVariantDark(): Color = colorResource(R.color.outline_variant_dark)
@Composable fun md_inverseSurfaceDark(): Color = colorResource(R.color.inverse_surface_dark)
@Composable fun md_inverseOnSurfaceDark(): Color = colorResource(R.color.inverse_on_surface_dark)
@Composable fun md_inversePrimaryDark(): Color = colorResource(R.color.inverse_primary_dark)
@Composable fun md_surfaceTintDark(): Color = colorResource(R.color.surface_tint_dark)
@Composable fun md_scrimDark(): Color = colorResource(R.color.scrim_dark)

@Composable fun md_success(): Color = colorResource(R.color.success)
@Composable fun md_onSuccess(): Color = colorResource(R.color.on_success)
@Composable fun md_successContainer(): Color = colorResource(R.color.success_container)
@Composable fun md_onSuccessContainer(): Color = colorResource(R.color.on_success_container)

@Composable fun md_warning(): Color = colorResource(R.color.warning)
@Composable fun md_onWarning(): Color = colorResource(R.color.on_warning)
@Composable fun md_warningContainer(): Color = colorResource(R.color.warning_container)
@Composable fun md_onWarningContainer(): Color = colorResource(R.color.on_warning_container)

@Composable fun md_info(): Color = colorResource(R.color.info)
@Composable fun md_onInfo(): Color = colorResource(R.color.on_info)
@Composable fun md_infoContainer(): Color = colorResource(R.color.info_container)
@Composable fun md_onInfoContainer(): Color = colorResource(R.color.on_info_container)

@Composable fun md_successDark(): Color = colorResource(R.color.success_dark)
@Composable fun md_onSuccessDark(): Color = colorResource(R.color.on_success_dark)
@Composable fun md_successContainerDark(): Color = colorResource(R.color.success_container_dark)
@Composable fun md_onSuccessContainerDark(): Color = colorResource(R.color.on_success_container_dark)

@Composable fun md_warningDark(): Color = colorResource(R.color.warning_dark)
@Composable fun md_onWarningDark(): Color = colorResource(R.color.on_warning_dark)
@Composable fun md_warningContainerDark(): Color = colorResource(R.color.warning_container_dark)
@Composable fun md_onWarningContainerDark(): Color = colorResource(R.color.on_warning_container_dark)

@Composable fun md_infoDark(): Color = colorResource(R.color.info_dark)
@Composable fun md_onInfoDark(): Color = colorResource(R.color.on_info_dark)
@Composable fun md_infoContainerDark(): Color = colorResource(R.color.info_container_dark)
@Composable fun md_onInfoContainerDark(): Color = colorResource(R.color.on_info_container_dark)
