package com.lecomapp.liquefied.features.profile.presentation.components

object LocationOptions {
    val states = listOf(
        "Andhra Pradesh",
        "Arunachal Pradesh",
        "Assam",
        "Bihar",
        "Chhattisgarh",
        "Delhi",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jammu & Kashmir",
        "Jharkhand",
        "Karnataka",
        "Kerala",
        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        "Odisha",
        "Puducherry",
        "Punjab",
        "Rajasthan",
        "Sikkim",
        "Tamil Nadu",
        "Telangana",
        "Tripura",
        "Uttar Pradesh",
        "Uttarakhand",
        "West Bengal",
    )

    val cities = listOf(
        "Ahmedabad",
        "Bengaluru",
        "Bhopal",
        "Bhubaneswar",
        "Chandigarh",
        "Chennai",
        "Coimbatore",
        "Delhi",
        "Guwahati",
        "Hyderabad",
        "Indore",
        "Jaipur",
        "Kanpur",
        "Kochi",
        "Kolkata",
        "Lucknow",
        "Ludhiana",
        "Mumbai",
        "Nagpur",
        "Nashik",
        "Patna",
        "Pune",
        "Raipur",
        "Rajkot",
        "Ranchi",
        "Surat",
        "Thiruvananthapuram",
        "Vadodara",
        "Varanasi",
        "Visakhapatnam",
    )
}